name: AssetBundlesDev

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre_check:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "always"
          skip_after_successful_duplicate: "false"
          do_not_skip: "[]"
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: pre_check
    if: ${{ needs.pre_check.outputs.should_skip != 'true' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"

      # Checks-out your repository
      - uses: actions/checkout@v3
        with:
          repository: liusj5257/AzurLaneTools
          ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}
          ref: Dev
          fetch-depth: 1
          submodules: recursive


      - name: Checkout AssetBundles repo
        uses: actions/checkout@v3
        with:
          repository: liusj5257/AzurLaneAssetBundles
          ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}
          ref: Dev
          sparse-checkout: |
            TW
            JP
            EN
            KR
          path: AssetBundles
          fetch-depth: 1

      # - name: Checkout AzurLaneTachieHelper repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: liusj5257/AzurLaneTachieHelper
      #     ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}
      #     ref: main
      #     path: Assets/AzurLaneTachieHelper
      #     fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.10.11
          cache: "pip"
          cache-dependency-path: "Assets/requirements.txt"
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
        working-directory: Assets

      - name: Update AssetBundles
        run: |
          python test.py

        working-directory: Assets