# This is a basic workflow to help you get started with Actions

name: AssetBundles

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.TOOLS_REPOSITORY }}
          ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9        

      # Runs a single command using the runners shell

      - name: Update AssetBundles
        run: |
          cd Assets
          python main.py CN --repair
          python main.py JP --repair
          python main.py CN --repair
          python main.py JP --repair

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
