# This is a basic workflow to help you get started with Actions

name: AssetBundlesDev

# Controls when the workflow will run
on:
#   schedule:
#     - cron: "*/10 * * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"
          
      - uses: actions/checkout@v3
        with:
          repository: liusj5257/AzurLaneTools
          ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}
          ref: main
  
      - name: Checkout name repo
        uses: actions/checkout@v3
        with:
          repository: liusj5257/azurlane_anti_name
          ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}
          path: azurlane_anti_name
          sparse-checkout: AssetBundles

      - name: Checkout AssetBundles repo
        uses: actions/checkout@v3
        with:
          repository: liusj5257/AzurLaneAssetBundles
          ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}
          ref: main
          path: AssetBundles

      - name: Set up Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "Assets/requirements.txt"
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
        working-directory: Assets

      - name: Update AssetBundles
        run: |
          python test.py

        working-directory: Assets
