name: AssetBundlesMain

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre_check:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "always"
          skip_after_successful_duplicate: "false"
          do_not_skip: "[]"
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: pre_check
    if: ${{ needs.pre_check.outputs.should_skip != 'true' }}

    steps:
    
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"
          
      - uses: actions/checkout@v3
        with:
          repository: liusj5257/AzurLaneTools
          ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}
          ref: main
  
      - name: Checkout name repo
        uses: actions/checkout@v3
        with:
          repository: liusj5257/azurlane_anti_name
          ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}
          path: azurlane_anti_name
          sparse-checkout: AssetBundles

      - name: Checkout AssetBundles repo
        uses: actions/checkout@v3
        with:
          repository: liusj5257/AzurLaneAssetBundles
          ssh-key: ${{ secrets.TOOLS_DEPLOY_KEY }}
          ref: main
          path: AssetBundles

      - name: Set up Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "Assets/requirements.txt"
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
        working-directory: Assets

      - name: Update AssetBundles
        run: |
          python test.py

        working-directory: Assets
